# Generated by Django 4.0.4 on 2022-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='published')),
                ('company_name', models.CharField(max_length=60)),
                ('job_position', models.CharField(max_length=60)),
                ('lang_qualification', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('birth_date', models.DateTimeField('published', null=True)),
                ('gender', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=60)),
                ('lang_preference', models.CharField(max_length=60)),
            ],
        ),
    ]
