# Generated by Django 4.0.5 on 2022-06-05 13:04

from django.db import migrations, models
import konnektapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=konnektapi.models.pathTo),
        ),
    ]
