# Generated by Django 4.0.5 on 2022-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0002_jobseeker_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
