# Generated by Django 4.0.5 on 2022-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0002_alter_jobseeker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
