# Generated by Django 4.0.5 on 2022-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0003_alter_jobseeker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='phone_no',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_position',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='lang_qualification',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
