# Generated by Django 4.0.5 on 2022-06-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0004_alter_jobseeker_lang_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='age',
        ),
    ]
