# Generated by Django 4.0.5 on 2022-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0004_remove_jobpost_pub_date_jobpost_address_jobpost_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60, null=True)),
                ('address', models.TextField(null=True)),
                ('phone_no', models.CharField(max_length=60, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('job_position', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=60, null=True)),
                ('desc', models.TextField(null=True)),
                ('lang_qualification', models.CharField(max_length=60, null=True)),
                ('company_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='lang_qualification',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='type',
        ),
    ]
