# Generated by Django 4.0.5 on 2022-06-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0005_remove_jobseeker_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='profile_image',
            new_name='image',
        ),
    ]
