# Generated by Django 4.0.5 on 2022-06-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0006_rename_profile_image_jobseeker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
    ]
