# Generated by Django 4.0.5 on 2022-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnektapi', '0008_jobseeker_desc_jobseeker_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
